// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package appdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (
    id, user_id, provider, provider_user_id, provider_email, email_verified
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, provider, provider_user_id, provider_email, email_verified, created_at, updated_at
`

type CreateOAuthIdentityParams struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	ProviderEmail  string    `json:"provider_email"`
	EmailVerified  bool      `json:"email_verified"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderEmail,
		arg.EmailVerified,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordCredential = `-- name: CreatePasswordCredential :exec
INSERT INTO password_credentials (user_id, password_hash)
VALUES ($1, $2)
`

type CreatePasswordCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, createPasswordCredential, arg.UserID, arg.PasswordHash)
	return err
}

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (
    id, family_id, user_id, token_hash, expires_at, user_agent, ip_address
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, family_id, user_id, token_hash, expires_at, revoked_at, replaced_by, user_agent, ip_address, created_at, last_used_at
`

type CreateRefreshSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	FamilyID  uuid.UUID          `json:"family_id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent string             `json:"user_agent"`
	IpAddress string             `json:"ip_address"`
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, email_verified_at, display_name, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, email_verified_at, display_name, avatar_url, disabled_at, created_at, updated_at
`

type CreateUserParams struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       *string            `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT id, user_id, provider, provider_user_id, provider_email, email_verified, created_at, updated_at FROM oauth_identities
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthIdentityParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthIdentityForUser = `-- name: GetOAuthIdentityForUser :one
SELECT id, user_id, provider, provider_user_id, provider_email, email_verified, created_at, updated_at FROM oauth_identities
WHERE user_id = $1 AND provider = $2
`

type GetOAuthIdentityForUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetOAuthIdentityForUser(ctx context.Context, arg GetOAuthIdentityForUserParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityForUser, arg.UserID, arg.Provider)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordCredentialByEmail = `-- name: GetPasswordCredentialByEmail :one
SELECT u.id, u.email, u.email_verified_at, u.display_name, u.avatar_url, u.disabled_at, u.created_at, u.updated_at, pc.password_hash
FROM users u
JOIN password_credentials pc ON pc.user_id = u.id
WHERE u.email = $1
`

type GetPasswordCredentialByEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       *string            `json:"avatar_url"`
	DisabledAt      pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PasswordHash    string             `json:"password_hash"`
}

func (q *Queries) GetPasswordCredentialByEmail(ctx context.Context, email string) (GetPasswordCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByEmail, email)
	var i GetPasswordCredentialByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getRefreshSessionByTokenHash = `-- name: GetRefreshSessionByTokenHash :one
SELECT id, family_id, user_id, token_hash, expires_at, revoked_at, replaced_by, user_agent, ip_address, created_at, last_used_at FROM refresh_sessions WHERE token_hash = $1
`

func (q *Queries) GetRefreshSessionByTokenHash(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByTokenHash, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.id AS session_id,
    s.revoked_at AS session_revoked_at,
    s.expires_at AS session_expires_at,
    u.id, u.email, u.email_verified_at, u.display_name, u.avatar_url, u.disabled_at, u.created_at, u.updated_at
FROM refresh_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
`

type GetSessionWithUserRow struct {
	SessionID        uuid.UUID          `json:"session_id"`
	SessionRevokedAt pgtype.Timestamptz `json:"session_revoked_at"`
	SessionExpiresAt pgtype.Timestamptz `json:"session_expires_at"`
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	DisplayName      string             `json:"display_name"`
	AvatarUrl        *string            `json:"avatar_url"`
	DisabledAt       pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, id uuid.UUID) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, id)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionRevokedAt,
		&i.SessionExpiresAt,
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, display_name, avatar_url, disabled_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, display_name, avatar_url, disabled_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPasswordCredentialForUser = `-- name: HasPasswordCredentialForUser :one
SELECT EXISTS (
    SELECT 1 FROM password_credentials WHERE user_id = $1
)
`

func (q *Queries) HasPasswordCredentialForUser(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPasswordCredentialForUser, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listOAuthProvidersForUser = `-- name: ListOAuthProvidersForUser :many
SELECT provider FROM oauth_identities
WHERE user_id = $1
ORDER BY provider
`

func (q *Queries) ListOAuthProvidersForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOAuthProvidersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionWithUser = `-- name: LockSessionWithUser :one
SELECT
    s.id AS session_id,
    s.revoked_at AS session_revoked_at,
    s.expires_at AS session_expires_at,
    u.id, u.email, u.email_verified_at, u.display_name, u.avatar_url, u.disabled_at, u.created_at, u.updated_at
FROM refresh_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
FOR SHARE OF s
`

type LockSessionWithUserRow struct {
	SessionID        uuid.UUID          `json:"session_id"`
	SessionRevokedAt pgtype.Timestamptz `json:"session_revoked_at"`
	SessionExpiresAt pgtype.Timestamptz `json:"session_expires_at"`
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	DisplayName      string             `json:"display_name"`
	AvatarUrl        *string            `json:"avatar_url"`
	DisabledAt       pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LockSessionWithUser(ctx context.Context, id uuid.UUID) (LockSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, lockSessionWithUser, id)
	var i LockSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionRevokedAt,
		&i.SessionExpiresAt,
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUserByID = `-- name: LockUserByID :one
SELECT id, email, email_verified_at, display_name, avatar_url, disabled_at, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, lockUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, $2), updated_at = now()
WHERE id = $1
`

type MarkUserEmailVerifiedParams struct {
	ID              uuid.UUID          `json:"id"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, arg.ID, arg.EmailVerifiedAt)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE refresh_sessions
SET revoked_at = COALESCE(revoked_at, $2)
WHERE user_id = $1
`

type RevokeAllUserSessionsParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.UserID, arg.RevokedAt)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_sessions
SET revoked_at = COALESCE(revoked_at, $2)
WHERE family_id = $1
`

type RevokeRefreshFamilyParams struct {
	FamilyID  uuid.UUID          `json:"family_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, arg.FamilyID, arg.RevokedAt)
	return err
}

const rotateRefreshSession = `-- name: RotateRefreshSession :execrows
UPDATE refresh_sessions
SET revoked_at = $2, replaced_by = $3, last_used_at = $2
WHERE id = $1 AND revoked_at IS NULL AND expires_at > $2
`

type RotateRefreshSessionParams struct {
	ID         uuid.UUID          `json:"id"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
}

func (q *Queries) RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateRefreshSession, arg.ID, arg.RevokedAt, arg.ReplacedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfileFromOAuth = `-- name: UpdateUserProfileFromOAuth :exec
UPDATE users
SET display_name = CASE
        WHEN $1::text <> '' THEN $1
        ELSE display_name
    END,
    avatar_url = COALESCE($2, avatar_url),
    updated_at = now()
WHERE id = $3
`

type UpdateUserProfileFromOAuthParams struct {
	DisplayName string    `json:"display_name"`
	AvatarUrl   *string   `json:"avatar_url"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfileFromOAuth(ctx context.Context, arg UpdateUserProfileFromOAuthParams) error {
	_, err := q.db.Exec(ctx, updateUserProfileFromOAuth, arg.DisplayName, arg.AvatarUrl, arg.ID)
	return err
}
