// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package appdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Database struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	ConnectionCiphertext []byte             `json:"connection_ciphertext"`
	ConnectionNonce      []byte             `json:"connection_nonce"`
	EncryptionKeyVersion int16              `json:"encryption_key_version"`
	CreatedBy            uuid.UUID          `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type DatabaseExtension struct {
	DatabaseID      uuid.UUID          `json:"database_id"`
	Extension       string             `json:"extension"`
	SelectedBy      uuid.UUID          `json:"selected_by"`
	SelectedAt      pgtype.Timestamptz `json:"selected_at"`
	IntervalSeconds int32              `json:"interval_seconds"`
	LastInterval    pgtype.Timestamptz `json:"last_interval"`
	NextInterval    pgtype.Timestamptz `json:"next_interval"`
}

type OauthIdentity struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	ProviderEmail  string             `json:"provider_email"`
	EmailVerified  bool               `json:"email_verified"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Plan           string             `json:"plan"`
	AnalyticsStore string             `json:"analytics_store"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMembership struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PasswordCredential struct {
	UserID       uuid.UUID          `json:"user_id"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RefreshSession struct {
	ID         uuid.UUID          `json:"id"`
	FamilyID   uuid.UUID          `json:"family_id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	UserAgent  string             `json:"user_agent"`
	IpAddress  string             `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       *string            `json:"avatar_url"`
	DisabledAt      pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
