// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package appdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (
    id, organization_id, name, slug, connection_ciphertext,
    connection_nonce, encryption_key_version, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, name, slug, connection_ciphertext, connection_nonce, encryption_key_version, created_by, created_at, updated_at
`

type CreateDatabaseParams struct {
	ID                   uuid.UUID `json:"id"`
	OrganizationID       uuid.UUID `json:"organization_id"`
	Name                 string    `json:"name"`
	Slug                 string    `json:"slug"`
	ConnectionCiphertext []byte    `json:"connection_ciphertext"`
	ConnectionNonce      []byte    `json:"connection_nonce"`
	EncryptionKeyVersion int16     `json:"encryption_key_version"`
	CreatedBy            uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.ConnectionCiphertext,
		arg.ConnectionNonce,
		arg.EncryptionKeyVersion,
		arg.CreatedBy,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.ConnectionCiphertext,
		&i.ConnectionNonce,
		&i.EncryptionKeyVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, name, slug, plan, analytics_store, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.AnalyticsStore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationMembership = `-- name: CreateOrganizationMembership :one
INSERT INTO organization_memberships (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING organization_id, user_id, role, created_at, updated_at
`

type CreateOrganizationMembershipParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateOrganizationMembership(ctx context.Context, arg CreateOrganizationMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createOrganizationMembership, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMembership
	err := row.Scan(
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDatabase = `-- name: DeleteDatabase :execrows
DELETE FROM databases
WHERE id = $1 AND organization_id = $2
`

type DeleteDatabaseParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteDatabase(ctx context.Context, arg DeleteDatabaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDatabase, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deselectDatabaseExtension = `-- name: DeselectDatabaseExtension :execrows
DELETE FROM database_extensions
WHERE database_id = $1 AND extension = $2
`

type DeselectDatabaseExtensionParams struct {
	DatabaseID uuid.UUID `json:"database_id"`
	Extension  string    `json:"extension"`
}

func (q *Queries) DeselectDatabaseExtension(ctx context.Context, arg DeselectDatabaseExtensionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deselectDatabaseExtension, arg.DatabaseID, arg.Extension)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDatabaseBySlugForOrganization = `-- name: GetDatabaseBySlugForOrganization :one
SELECT id, organization_id, name, slug, connection_ciphertext, connection_nonce, encryption_key_version, created_by, created_at, updated_at FROM databases
WHERE slug = $1 AND organization_id = $2
FOR UPDATE
`

type GetDatabaseBySlugForOrganizationParams struct {
	Slug           string    `json:"slug"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetDatabaseBySlugForOrganization(ctx context.Context, arg GetDatabaseBySlugForOrganizationParams) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabaseBySlugForOrganization, arg.Slug, arg.OrganizationID)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.ConnectionCiphertext,
		&i.ConnectionNonce,
		&i.EncryptionKeyVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseForOrganization = `-- name: GetDatabaseForOrganization :one
SELECT id, organization_id, name, slug, connection_ciphertext, connection_nonce, encryption_key_version, created_by, created_at, updated_at FROM databases
WHERE id = $1 AND organization_id = $2
`

type GetDatabaseForOrganizationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetDatabaseForOrganization(ctx context.Context, arg GetDatabaseForOrganizationParams) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabaseForOrganization, arg.ID, arg.OrganizationID)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.ConnectionCiphertext,
		&i.ConnectionNonce,
		&i.EncryptionKeyVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByIDForUser = `-- name: GetOrganizationByIDForUser :one
SELECT o.id, o.name, o.slug, o.plan, o.analytics_store, o.created_at, o.updated_at, m.role
FROM organizations o
JOIN organization_memberships m ON m.organization_id = o.id
WHERE o.id = $1 AND m.user_id = $2
`

type GetOrganizationByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetOrganizationByIDForUserRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Plan           string             `json:"plan"`
	AnalyticsStore string             `json:"analytics_store"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Role           string             `json:"role"`
}

func (q *Queries) GetOrganizationByIDForUser(ctx context.Context, arg GetOrganizationByIDForUserParams) (GetOrganizationByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByIDForUser, arg.ID, arg.UserID)
	var i GetOrganizationByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.AnalyticsStore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getOrganizationBySlugForUser = `-- name: GetOrganizationBySlugForUser :one
SELECT o.id, o.name, o.slug, o.plan, o.analytics_store, o.created_at, o.updated_at, m.role
FROM organizations o
JOIN organization_memberships m ON m.organization_id = o.id
WHERE o.slug = $1 AND m.user_id = $2
`

type GetOrganizationBySlugForUserParams struct {
	Slug   string    `json:"slug"`
	UserID uuid.UUID `json:"user_id"`
}

type GetOrganizationBySlugForUserRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Plan           string             `json:"plan"`
	AnalyticsStore string             `json:"analytics_store"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Role           string             `json:"role"`
}

func (q *Queries) GetOrganizationBySlugForUser(ctx context.Context, arg GetOrganizationBySlugForUserParams) (GetOrganizationBySlugForUserRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlugForUser, arg.Slug, arg.UserID)
	var i GetOrganizationBySlugForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.AnalyticsStore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const listDatabaseExtensions = `-- name: ListDatabaseExtensions :many
SELECT extension, interval_seconds FROM database_extensions
WHERE database_id = $1
ORDER BY extension
`

type ListDatabaseExtensionsRow struct {
	Extension       string `json:"extension"`
	IntervalSeconds int32  `json:"interval_seconds"`
}

func (q *Queries) ListDatabaseExtensions(ctx context.Context, databaseID uuid.UUID) ([]ListDatabaseExtensionsRow, error) {
	rows, err := q.db.Query(ctx, listDatabaseExtensions, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatabaseExtensionsRow{}
	for rows.Next() {
		var i ListDatabaseExtensionsRow
		if err := rows.Scan(&i.Extension, &i.IntervalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesForOrganization = `-- name: ListDatabasesForOrganization :many
SELECT id, organization_id, name, slug, connection_ciphertext, connection_nonce, encryption_key_version, created_by, created_at, updated_at FROM databases
WHERE organization_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListDatabasesForOrganization(ctx context.Context, organizationID uuid.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.ConnectionCiphertext,
			&i.ConnectionNonce,
			&i.EncryptionKeyVersion,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.slug, o.plan, o.analytics_store, o.created_at, o.updated_at, m.role
FROM organizations o
JOIN organization_memberships m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at, o.id
`

type ListOrganizationsForUserRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Plan           string             `json:"plan"`
	AnalyticsStore string             `json:"analytics_store"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Role           string             `json:"role"`
}

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsForUserRow{}
	for rows.Next() {
		var i ListOrganizationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.AnalyticsStore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganizationBySlugForUser = `-- name: LockOrganizationBySlugForUser :one
SELECT o.id, o.name, o.slug, o.plan, o.analytics_store, o.created_at, o.updated_at, m.role
FROM organizations o
JOIN organization_memberships m ON m.organization_id = o.id
WHERE o.slug = $1 AND m.user_id = $2
FOR UPDATE OF o
FOR SHARE OF m
`

type LockOrganizationBySlugForUserParams struct {
	Slug   string    `json:"slug"`
	UserID uuid.UUID `json:"user_id"`
}

type LockOrganizationBySlugForUserRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Plan           string             `json:"plan"`
	AnalyticsStore string             `json:"analytics_store"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Role           string             `json:"role"`
}

func (q *Queries) LockOrganizationBySlugForUser(ctx context.Context, arg LockOrganizationBySlugForUserParams) (LockOrganizationBySlugForUserRow, error) {
	row := q.db.QueryRow(ctx, lockOrganizationBySlugForUser, arg.Slug, arg.UserID)
	var i LockOrganizationBySlugForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.AnalyticsStore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const selectDatabaseExtension = `-- name: SelectDatabaseExtension :exec
INSERT INTO database_extensions (database_id, extension, interval_seconds, selected_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (database_id, extension) DO UPDATE
SET interval_seconds = EXCLUDED.interval_seconds,
    selected_by = EXCLUDED.selected_by,
    selected_at = now()
`

type SelectDatabaseExtensionParams struct {
	DatabaseID      uuid.UUID `json:"database_id"`
	Extension       string    `json:"extension"`
	IntervalSeconds int32     `json:"interval_seconds"`
	SelectedBy      uuid.UUID `json:"selected_by"`
}

func (q *Queries) SelectDatabaseExtension(ctx context.Context, arg SelectDatabaseExtensionParams) error {
	_, err := q.db.Exec(ctx, selectDatabaseExtension,
		arg.DatabaseID,
		arg.Extension,
		arg.IntervalSeconds,
		arg.SelectedBy,
	)
	return err
}

const updateOrganizationAnalyticsStore = `-- name: UpdateOrganizationAnalyticsStore :one
UPDATE organizations
SET analytics_store = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, plan, analytics_store, created_at, updated_at
`

type UpdateOrganizationAnalyticsStoreParams struct {
	ID             uuid.UUID `json:"id"`
	AnalyticsStore string    `json:"analytics_store"`
}

func (q *Queries) UpdateOrganizationAnalyticsStore(ctx context.Context, arg UpdateOrganizationAnalyticsStoreParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationAnalyticsStore, arg.ID, arg.AnalyticsStore)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.AnalyticsStore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
