// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probes.sql

package appdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProbeLog = `-- name: CreateProbeLog :exec
INSERT INTO probe_logs (id, database_ids, reason, started_at)
VALUES ($1, $2, $3, $4)
`

type CreateProbeLogParams struct {
	ID          uuid.UUID          `json:"id"`
	DatabaseIds []uuid.UUID        `json:"database_ids"`
	Reason      string             `json:"reason"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateProbeLog(ctx context.Context, arg CreateProbeLogParams) error {
	_, err := q.db.Exec(ctx, createProbeLog,
		arg.ID,
		arg.DatabaseIds,
		arg.Reason,
		arg.StartedAt,
	)
	return err
}

const finishProbeLog = `-- name: FinishProbeLog :execrows
UPDATE probe_logs AS logs
SET completed_at = $1
WHERE logs.id = $2
  AND logs.completed_at IS NULL
  AND $1 >= logs.started_at
  AND NOT EXISTS (
      SELECT 1 FROM unnest(logs.database_ids) AS targets(database_id)
      WHERE NOT EXISTS (
          SELECT 1 FROM probe_database_snapshots AS snapshots
          WHERE snapshots.event_id = logs.id
            AND snapshots.database_id = targets.database_id
      )
  )
  AND NOT EXISTS (
      SELECT 1 FROM probe_database_snapshots AS snapshots
      WHERE snapshots.event_id = logs.id
        AND snapshots.completed_at > $1
  )
`

type FinishProbeLogParams struct {
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	EventID     uuid.UUID          `json:"event_id"`
}

func (q *Queries) FinishProbeLog(ctx context.Context, arg FinishProbeLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishProbeLog, arg.CompletedAt, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProbeLog = `-- name: GetProbeLog :one
SELECT id, database_ids, reason, started_at, completed_at FROM probe_logs WHERE id = $1
`

func (q *Queries) GetProbeLog(ctx context.Context, id uuid.UUID) (ProbeLog, error) {
	row := q.db.QueryRow(ctx, getProbeLog, id)
	var i ProbeLog
	err := row.Scan(
		&i.ID,
		&i.DatabaseIds,
		&i.Reason,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listProbeDatabaseSnapshots = `-- name: ListProbeDatabaseSnapshots :many
SELECT snapshots.event_id, snapshots.database_id, snapshots.database_status, snapshots.status, snapshots.error_message, snapshots.extensions, snapshots.started_at, snapshots.completed_at, logs.reason
FROM probe_database_snapshots AS snapshots
JOIN probe_logs AS logs ON logs.id = snapshots.event_id
WHERE snapshots.event_id = $1
ORDER BY snapshots.started_at, snapshots.database_id
`

type ListProbeDatabaseSnapshotsRow struct {
	EventID        uuid.UUID          `json:"event_id"`
	DatabaseID     uuid.UUID          `json:"database_id"`
	DatabaseStatus string             `json:"database_status"`
	Status         string             `json:"status"`
	ErrorMessage   string             `json:"error_message"`
	Extensions     []byte             `json:"extensions"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Reason         string             `json:"reason"`
}

func (q *Queries) ListProbeDatabaseSnapshots(ctx context.Context, eventID uuid.UUID) ([]ListProbeDatabaseSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listProbeDatabaseSnapshots, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProbeDatabaseSnapshotsRow{}
	for rows.Next() {
		var i ListProbeDatabaseSnapshotsRow
		if err := rows.Scan(
			&i.EventID,
			&i.DatabaseID,
			&i.DatabaseStatus,
			&i.Status,
			&i.ErrorMessage,
			&i.Extensions,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProbeLog = `-- name: LockProbeLog :one
SELECT id, database_ids, reason, started_at, completed_at FROM probe_logs WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockProbeLog(ctx context.Context, id uuid.UUID) (ProbeLog, error) {
	row := q.db.QueryRow(ctx, lockProbeLog, id)
	var i ProbeLog
	err := row.Scan(
		&i.ID,
		&i.DatabaseIds,
		&i.Reason,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const saveProbeDatabaseSnapshot = `-- name: SaveProbeDatabaseSnapshot :execrows
INSERT INTO probe_database_snapshots (
    event_id, database_id, database_status, status, error_message,
    extensions, started_at, completed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (event_id, database_id) DO UPDATE
SET event_id = EXCLUDED.event_id
WHERE probe_database_snapshots.database_status = EXCLUDED.database_status
  AND probe_database_snapshots.status = EXCLUDED.status
  AND probe_database_snapshots.error_message = EXCLUDED.error_message
  AND probe_database_snapshots.extensions = EXCLUDED.extensions
  AND probe_database_snapshots.started_at = EXCLUDED.started_at
  AND probe_database_snapshots.completed_at = EXCLUDED.completed_at
`

type SaveProbeDatabaseSnapshotParams struct {
	EventID        uuid.UUID          `json:"event_id"`
	DatabaseID     uuid.UUID          `json:"database_id"`
	DatabaseStatus string             `json:"database_status"`
	Status         string             `json:"status"`
	ErrorMessage   string             `json:"error_message"`
	Extensions     []byte             `json:"extensions"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) SaveProbeDatabaseSnapshot(ctx context.Context, arg SaveProbeDatabaseSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveProbeDatabaseSnapshot,
		arg.EventID,
		arg.DatabaseID,
		arg.DatabaseStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.Extensions,
		arg.StartedAt,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
